sudo: required
dist: trusty
language:
  - java
jdk:
  - oraclejdk8  # Building Bazel requires JDK8.
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg'
      - sourceline: 'deb [arch=amd64] http://packages.cloud.google.com/apt cloud-sdk-trusty main'
        key_url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
    packages:
      - bazel
      - google-cloud-sdk
      - kubectl

before_install:
  # Log into GCR
  - docker login -u _json_key -p "${GOOGLE_JSON_KEY}" https://us.gcr.io
  # Log into gcloud
  - echo -n "${GOOGLE_JSON_KEY}" > keyfile.json
  - gcloud auth activate-service-account --key-file keyfile.json
  - rm -f keyfile.json
  - gcloud config set core/project rules-k8s
  - gcloud config set compute/zone us-central1-f
  - gcloud container clusters get-credentials testing

install:
  - go get -u github.com/bazelbuild/buildifier/buildifier

script:
  # Check our installs.
  - bazel version
  - gcloud version
  - kubectl version

  # Check that all of our tools and samples build
  - bazel clean && bazel build //...
  # Check that all of our tests pass
  - bazel clean && bazel test //...

  # Check for issues with the format of our bazel config files.
  - buildifier -mode=check $(find . -name BUILD -type f)
  - buildifier -mode=check $(find . -name WORKSPACE -type f)
  - buildifier -mode=check $(find . -name '*.bzl' -type f)

  # Run end-to-end integration testing.
  # First, GRPC.
  - ./examples/hellogrpc/e2e-test.sh cc
  - ./examples/hellogrpc/e2e-test.sh java
  - ./examples/hellogrpc/e2e-test.sh go
  - ./examples/hellogrpc/e2e-test.sh py
  # Second, HTTP.
  - ./examples/hellohttp/e2e-test.sh java
  - ./examples/hellohttp/e2e-test.sh go
  - ./examples/hellohttp/e2e-test.sh py
  - ./examples/hellohttp/e2e-test.sh nodejs
  # Third, TODO Controller.
  - ./examples/todocontroller/e2e-test.sh py
